# Generated by Django 6.0.1 on 2026-02-14 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_post_updated_at_post_video_alter_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='date_posted',
        ),
    ]
