# Generated by Django 6.0.1 on 2026-02-25 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_category_post_is_approved_post_is_hub_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.RemoveField(
            model_name='post',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='post',
            name='is_hub',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
